name:                 workout-tracker
version:              0.1.0.0
visibility:           public
id:                   workout-tracker-0.1.0.0-inplace
key:                  workout-tracker-0.1.0.0-inplace
license:              MIT
maintainer:           heldalteodor@gmail.com
author:               Teodor Heldal
abi:                  inplace
exposed:              True
exposed-modules:
    Workout.API Workout.App Workout.Calculations Workout.Domain
    Workout.Parser Workout.Server

import-dirs:
    "/Users/teodorheldal/Documents/Programmering /inf221/Project/dist-newstyle/build/aarch64-osx/ghc-9.4.8/workout-tracker-0.1.0.0/build"

library-dirs:
    "/Users/teodorheldal/Documents/Programmering /inf221/Project/dist-newstyle/build/aarch64-osx/ghc-9.4.8/workout-tracker-0.1.0.0/build"

library-dirs-static:
    "/Users/teodorheldal/Documents/Programmering /inf221/Project/dist-newstyle/build/aarch64-osx/ghc-9.4.8/workout-tracker-0.1.0.0/build"

dynamic-library-dirs:
    "/Users/teodorheldal/Documents/Programmering /inf221/Project/dist-newstyle/build/aarch64-osx/ghc-9.4.8/workout-tracker-0.1.0.0/build"

data-dir:
    "/Users/teodorheldal/Documents/Programmering /inf221/Project/."

hs-libraries:         HSworkout-tracker-0.1.0.0-inplace
depends:
    sn-2.2.3.0-83356a1c base-4.17.2.1 bytestring-0.11.5.3
    containers-0.6.7 mgprsc-9.7.0-fb2eecdf mtl-2.2.2
    srvnt-0.20.3.0-e2d71439 srvnt-srvr-0.20.3.0-bee1ad52 text-2.0.2
    transformers-0.5.6.2 wrp-3.4.12-6f2d2f1e

haddock-interfaces:
    "/Users/teodorheldal/Documents/Programmering /inf221/Project/dist-newstyle/build/aarch64-osx/ghc-9.4.8/workout-tracker-0.1.0.0/doc/html/workout-tracker/workout-tracker.haddock"

haddock-html:
    "/Users/teodorheldal/Documents/Programmering /inf221/Project/dist-newstyle/build/aarch64-osx/ghc-9.4.8/workout-tracker-0.1.0.0/doc/html/workout-tracker"
